
'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle, Code, Clock, BrainCircuit } from 'lucide-react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import React from 'react';

export default function CodingQuizInstructionsPage() {
  const searchParams = useSearchParams();
  const topics = searchParams.get('topics');
  const difficulty = searchParams.get('difficulty');
  const numQuestions = searchParams.get('numQuestions') || '3';

  const quizParams = new URLSearchParams({
    topics: topics || '',
    difficulty: difficulty || '',
    numQuestions: numQuestions,
  });

  return (
    <main className="flex-1 overflow-auto p-4 sm:p-6 lg:p-8">
      <div className="max-w-4xl mx-auto">
        <Card className="shadow-lg">
          <CardHeader className="text-center">
            <Code className="mx-auto h-12 w-12 text-primary mb-4" />
            <h1 className="font-headline text-4xl font-bold">Coding Quiz Instructions</h1>
            <CardDescription className="text-lg">
              Get ready to test your skills! Here's what you need to know.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-8 px-8 py-6">
            <div className="space-y-4">
                <h2 className="font-semibold text-2xl">Quiz Details</h2>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground bg-muted p-4 rounded-lg">
                    <li><strong className="text-foreground">Topics:</strong> {topics}</li>
                    <li><strong className="text-foreground">Difficulty:</strong> <span className="capitalize">{difficulty}</span></li>
                    <li><strong className="text-foreground">Number of Questions:</strong> {numQuestions}</li>
                </ul>
            </div>

            <div className="space-y-4">
              <h2 className="font-semibold text-2xl">How It Works</h2>
              <div className="grid gap-4 md:grid-cols-3">
                <div className="flex items-start gap-4">
                  <div className="bg-primary/10 text-primary rounded-full p-2">
                    <BrainCircuit className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold">AI-Generated Questions</h3>
                    <p className="text-muted-foreground text-sm">You'll be presented with questions generated by our AI based on your chosen topics and difficulty.</p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="bg-primary/10 text-primary rounded-full p-2">
                    <Clock className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold">Solve the Problems</h3>
                    <p className="text-muted-foreground text-sm">Write your code in the provided editor for each question. Take your time, there's no visible timer.</p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="bg-primary/10 text-primary rounded-full p-2">
                    <CheckCircle className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold">Get Instant Feedback</h3>
                    <p className="text-muted-foreground text-sm">After you complete the quiz, our AI will analyze your answers and provide detailed feedback on your performance.</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="text-center pt-4">
              <Button asChild size="lg">
                <Link href={`/dashboard/coding-quiz/quiz?${quizParams.toString()}`}>Start Quiz</Link>
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
