
import { config } from 'dotenv';
config();

// This is an autogenerated file from Firebase Studio.
// You can export functions from here to be discovered by the Genkit CLI.

import '@/ai/flows/generate-interview-questions.ts';
import '@/ai/flows/summarize-user-feedback.ts';
import '@/ai/flows/generate-code-explanation.ts';
import '@/ai/flows/generate-code-snippet.ts';
import '@/ai/flows/generate-coding-questions.ts';
import '@/ai/flows/analyze-coding-answers.ts';
import '@/ai/flows/generate-syllabus.ts';
import '@/ai/flows/generate-study-notes.ts';
import '@/ai/flows/generate-interview-feedback.ts';
import '@/ai/flows/enhance-resume.ts';
import '@/ai/flows/deepgram-tts.ts';
import '@/ai/flows/interview-agent.ts';
